<?xml version="1.0"?>
<package format="3">
  <name>sim_bringup</name>
  <version>0.0.1</version>
  <description>Combined simulation bringup for LimX robot</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>robot_hw</exec_depend>
  <exec_depend>robot_visualization</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
